# -*- coding: utf-8 -*-
"""1186.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cyky5y-2jLWHuSb5H4nURWTEYHl51Q1d
"""

def maximumSum(arr):
    n=len(arr)
    ans=float('-inf')
    dp=[[float('-inf')]*2 for _ in range(n+1)]
    for i in range(n):
        dp[i+1][0]=max(dp[i][0]+arr[i],arr[i])
        dp[i+1][1]=max(dp[i][1]+arr[i],dp[i][0])
        ans=max(ans,dp[i+1][0],dp[i+1][1])
    return ans

maximumSum([1,2,-1,3])